spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  application:
    name: main-service
  config:
    import: configserver:http://config-service-hls:8888

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

server:
  port: 8083