spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-admin-password: password
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true