spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    username: postgres
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    default-schema: "public"
    change-log: classpath:db/changesets.xml

jwt:
  secret:
    access_decoded: secret-access-123456789012345678901234567890
    access: c2VjcmV0LWFjY2Vzcy0xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
    refresh_decoded: secret-refresh-123456789012345678901234567890
    refresh: c2VjcmV0LXJlZnJlc2gtMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkw
#    access_decoded: ${JWT_SECRET_ACCESS_DECODED}
#    access: ${JWT_SECRET_ACCESS}
#    refresh_decoded: ${JWT_SECRET_REFRESH_DECODED}
#    refresh: ${JWT_SECRET_REFRESH}

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
