spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
#        web-admin-password: 123456789012
        web-allow-others: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: user
    driverClassName: org.postgresql.Driver
  #    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create
  liquibase:
    enabled: true
    default-schema: "public"
    change-log: classpath:db/changesets.xml

jwt:
  secret:
    access_decoded: secret-access-123456789012345678901234567890
    access: c2VjcmV0LWFjY2Vzcy0xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
    refresh_decoded: secret-refresh-123456789012345678901234567890
    refresh: c2VjcmV0LXJlZnJlc2gtMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkw
