spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    default-schema: "public"
    change-log: classpath:db/changesets.xml
  profiles:
    active: dev

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true