spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    default-schema: "f_tester_lab"
    change-log: classpath:db/changesets.xml

jwt:
  secret:
    access_decoded: secret-access-123456789012345678901234567890
    access: c2VjcmV0LWFjY2Vzcy0xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
    refresh_decoded: secret-refresh-123456789012345678901234567890
    refresh: c2VjcmV0LXJlZnJlc2gtMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkw

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

baseUrl: http://localhost:8080