spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    default-schema: "f_tester_lab"
    change-log: classpath:db/changesets.xml

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

baseUrl: http://localhost:8080