spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  application:
    name: main-service
  #  datasource:
#    url: jdbc:postgresql://postgres:5432/postgres
#    username: postgres
#    password: user
#    driverClassName: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#  liquibase:
#    enabled: true
#    default-schema: f_tester_lab
#    change-log: classpath:db/changesets.xml
  config:
    import: configserver:http://localhost:8888

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

server:
  port: 8083

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true